[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[workspace]
resolver = "2"
members = [
  "rs-lib",
  "wasm",
]

[workspace.dependencies]
deno_error = "0.5.6"
sys_traits = { version = "0.1.9", features = ["real"] }
